### ISSUE TITLE
[QUESTION] How to deal with streamers that rarely streams, i.e `content:null`

### ISSUE THREAD

**Issue by kman3107** [4Z0N4S/Callisto#10]
After the recent change [6d7a10d](https://github.com/4Z0N4S/Callisto/commit/6d7a10d19f5d2790775a6408ae7a6a9d95fd094f) I am now getting a error response, because the streamer my app is waiting for rarely streams and their content is deleted. Is there a way to deal with getting a 200 response with null content?
Example:
[INFO] 2024-07-30 22:14:25 OFFLINE! Checking again in 1 minute.
[ERROR] 2024-08-20 10:05:01 Error Status code: 200 Response: {"code":200,"message":null,"content":null}

I know I can safely ignore it, but, it is flooding my log so I was just wondering if you knew of a quick way to deal with streams like this.

**Comment by 4Z0N4S** [comment]
`{
  "code": 200,
  "message": null,
  "content": {
    "liveId": 7606151,
    "liveTitle": "골골",
    "status": "CLOSE",
  }
}`  

For normal channels, the API responds as above. 
On the other hand, for channels that have not been broadcast for a long time, the API responds as follows.

`{
  "code": 200,
  "message": null,
  "content": null
}`

So it shows an error response. I'll reflect on it in the next change

**Comment by 4Z0N4S** [comment]
I've made some changes. c800ca1

**Comment by kman3107** [comment]
Tested and works as intended. Awesomesauce 👍
