### ISSUE TITLE
[INFO] Streamlink 6.7.4 now has chzzk plugin

### ISSUE THREAD

**Issue by kman3107** [4Z0N4S/Callisto#4]
As can be seen in the [6.7.4 release](https://github.com/streamlink/streamlink/releases/tag/6.7.4), Streamlink now supports chzzk natively.
From release note:
>chzzk: new plugin (https://github.com/streamlink/streamlink/pull/5731)

CLI example:
`streamlink --http-cookie NID_AUT=xXxXxXxXxXxXxXx --http-cookie NID_SES=xXxXxXxXxXxXxXx https://chzzk.naver.com/live/xXxXxXxXxXxXxXx`

Tested and it works for me.
Just wanted to give you a heads-up.

**************************

On another note your docker container works just fine when streamer is already online,  
but, throws and error when the streamer is offline.
```bash
Traceback (most recent call last):
  File "/home/callisto/callisto.py", line 67, in <module>
    check_stream()
  File "/home/callisto/callisto.py", line 50, in check_stream
    naver_status = check_naver_status()     
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/callisto/callisto.py", line 31, in check_naver_status
    return response.json().get('content', {}).get('status')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'```

**Comment by 4Z0N4S** [comment]
Thank you for letting me know.
