### ISSUE TITLE
상대가 다시보기를 공개하지않으면 녹화가안되는건가요?

### ISSUE THREAD

**Issue by Bewefau** [4Z0N4S/Callisto#8]
파일은 생성되고 용량은 차지하는데 녹화된 영상을 틀면 재생이안됩니다..

**Comment by 4Z0N4S** [comment]
다시보기를 공개하지 않는 스트리머의 경우에도 정상 작동합니다.

**Comment by Bewefau** [comment]
> 다시보기를 공개하지 않는 스트리머의 경우에도 정상 작동합니다.

특정 방송만 그래서 원인을 모르겠네요 ㅠㅠ 답변감사합니다
