### ISSUE TITLE
연령제한 채널 녹화 관련

### ISSUE THREAD

**Issue by Grinoy** [4Z0N4S/Callisto#9]
![image](https://github.com/user-attachments/assets/07412932-ea1d-420a-b142-ea9655e7ab19)

안녕하세요 연령제한 채널이 녹화가 안되어서 그런데 혹시라도 쿠키관련 문제인지 아니면 지원하지 않는 기능인지 궁금하여 문의 남깁니다

**Comment by 4Z0N4S** [comment]
![화면 캡처 2024-08-06 192639](https://github.com/user-attachments/assets/45a97225-9138-4743-9096-5928a265bc1c)

연령제한 컨텐츠 녹화도 지원합니다. 쿠키 관련 문제로 보이는데 NID_AUT와 NID_SES를 새로 갱신하여 다시 녹화를 해보시겠어요?

**Comment by Grinoy** [comment]
감사합니다! 쿠키 변경하고 다시 빌드하니까 되네요! 좋은 프로그램 감사합니다

**Comment by Grinoy** [comment]
> ![화면 캡처 2024-08-06 192639](https://private-user-images.githubusercontent.com/15088456/355413268-45a97225-9138-4743-9096-5928a265bc1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDQ5NjUsIm5iZiI6MTcyMjk0NDY2NSwicGF0aCI6Ii8xNTA4ODQ1Ni8zNTU0MTMyNjgtNDVhOTcyMjUtOTEzOC00NzQzLTkwOTYtNTkyOGEyNjViYzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExNDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNzdhODNlNzk2ZmExMmZmOTk3YTE3OWIxYWNhYjk3ZjA4MWU3N2VmOThjYmJiZjg3NmYyZjkwMWFlM2U4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tFjnu7iCzfMem1vK65U0-7zWPleipVp1Phkc3_NFd_8)
> 
> 연령제한 컨텐츠 녹화도 지원합니다. 쿠키 관련 문제로 보이는데 NID_AUT와 NID_SES를 새로 갱신하여 다시 녹화를 해보시겠어요?
감사합니다! 쿠키 변경하고 다시 빌드하니까 되네요! 좋은 프로그램 감사합니다!
